name: Sync to Hugging Face

on:
  push:
    branches: [main]  # GitHubのmainブランチに変更があったときに動作

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://takumidake
:${HF_TOKEN}@huggingface.co/spaces/takumidake/SeihonApp
          git push hf main --force
