name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main  # mainブランチにpushされた時だけ実行

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # まず、GitHubリポジトリのコードをチェックアウトします
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # LFSファイルも取得する場合

      # 次に、Hugging Face Hubにファイルを強制的にpush（同期）します
      - name: Push to Hugging Face Hub
        env:
          # GitHubのSecretsに登録したHF_TOKENを使用
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Hugging FaceのSpaceリポジトリをリモートとして追加し、強制的にpushする
          git remote add space https://takumidakeseihon:$HF_TOKEN@huggingface.co/spaces/takumidakeseihon/seihon-app
          git push --force space main
